version: "3.9"
services:
  backend:
    build: ./backend
    container_name: board-backend
    env_file:
      - ./.env
    environment:
      - APP_BACKEND_CORS_ORIGINS=${APP_BACKEND_CORS_ORIGINS:-http://localhost:3000}
      - APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    volumes:
      - ./backend/app:/app/app
      - ./backend/media:/app/media
      - ./backend/db:/app/db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: board-frontend
    env_file:
      - ./.env
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-http://localhost:8000}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
